name: CodSpeed

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  codspeed:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v0
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed

      - uses: taiki-e/install-action@just

      - name: Build the benchmark target(s)
        run: just bench-build

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: just bench-run
          token: ${{ secrets.CODSPEED_TOKEN }}
